"""The script PyInstaller freezes — the standalone build's ``if __name__``.

A console script generated by pip is a two-line shim around
``media_ai.__main__:main``; a frozen bundle has no console scripts, so this is that
shim written out. It stays this thin on purpose: everything a build could get wrong
should be wrong in the same place for an installed package and a bundle, and code
that only ever runs when frozen is code the test suite never sees.
"""

from __future__ import annotations

import sys

from media_ai.__main__ import main

if __name__ == "__main__":
    sys.exit(main())
